### PR TITLE
Missed a PSD in ge_read_pfile.py - adding in for hbcd2

### PR DESCRIPTION
**Pull request by agudmundson**
Missed a PSD in ge_read_pfile.py - adding in for hbcd2... hopefully this will be the last fix for the GE hbcd sequence!

### CODE REVIEW

**Comment by agudmundson** [comment]
Good idea - the dataset I was just working on was just a phantom, so let me check with the owner if I'm able to add.

**Comment by wtclarke** [comment]
Any news on the dataset?


From: Aaron Gudmundson, PhD ***@***.***>
Date: Wednesday, 10 July 2024 at 15:45
To: wtclarke/spec2nii ***@***.***>
Cc: William Clarke ***@***.***>, Comment ***@***.***>
Subject: Re: [wtclarke/spec2nii] Missed a PSD in ge_read_pfile.py - adding in for hbcd2 (PR #145)

Good idea - the dataset I was just working on was just a phantom, so let me check with the owner if I'm able to add.

**Comment by agudmundson** [comment]
@wtclarke, did this ever get merged?

**Comment by wtclarke** [comment]
No, I'm quite keen to include data for regression testing.

**Pull request merged**
