### PR TITLE
Updates for GE HBCD Sequence

### PR DESCRIPTION
**Pull request by agudmundson**
More updates for the GE HBCD ISTHMUS sequence. Resolves issues with multichannel data, handles separated short TE and long TE scans that have the same PSD, and correctly uses HERCULES vs. ISTHMUS specific processing routines.

### CODE REVIEW

**Comment by agudmundson** [comment]
@wtclarke Getting a failure in the validation.py from the dimensions. The data is correctly shaped (you can see from my log statements just above the error.. Can you see an obvious reason as to why this might be having an issue?

**Comment by wtclarke** [comment]
Just looks like the dimensions are changed. Did you change the order? If so you will need to update the tests.

**Comment by wtclarke** [comment]
But it clearly has. The [test which was passing before these changes](https://github.com/wtclarke/spec2nii/blob/master/tests/test_ge_pfile.py#L344)  checks for
```
img = NIFTI_MRS(tmp_path / 'hbcd_edited.nii.gz')
assert img.shape == (1, 1, 1, 2048, 56, 8, 4)
```
but now that line is failing in the [test here](https://github.com/wtclarke/spec2nii/actions/runs/10834174043/job/30062698920?pr=147#step:6:178)

```
    00 _edited         (1, 1, 1, 2048, 56, 4, 8)
...
FAILED tests/test_ge_pfile.py::test_hbcd_isthmus - assert (1, 1, 1, 2048, 56, 4, ...) == (1, 1, 1, 2048, 56, 8, ...)
```

and [your changes](https://github.com/wtclarke/spec2nii/pull/147/files#diff-234482e9bc8efb7ac7c6b2ac13dd1de5e0930bbcb7269bf020e9bcd0a36bdebeR377) have swapped the last two dimensions.

**Comment by agudmundson** [comment]
@wtclarke I thought I switched them back after I received the error. Let me ensure I pushed those changes up.

**Comment by wtclarke** [comment]
Right, but that's just the labelling of the dimensions, the actual sizes are dictated by the data shape you've constructed.

**Comment by agudmundson** [comment]
@wtclarke ahh you're right, I forgot to update the reshaping. Looks to have passed now. Thank you!

**Comment by agudmundson** [comment]
@wtclarke Hi Will, did we need anything else or can we close this out?

**Pull request merged**
