### PR TITLE
FIX:UnicodeDecodeError while converting rda files

### PR DESCRIPTION
**Pull request by gaunab**
This fixes the UnixodeDecodeError while loading rda-Files:
https://github.com/wtclarke/spec2nii/issues/96#issue-1896123910

### CODE REVIEW

**Comment by wtclarke** [comment]
Hi @gaunab , thanks for the PR that's super useful. Could you a) provide any test data for this, and tweak this commit to undo all the formatting so that it's just the code changes?

**Comment by gaunab** [comment]
> Hi @gaunab , thanks for the PR that's super useful. Could you a) provide any test data for this, and tweak this commit to undo all the formatting so that it's just the code changes?

Where should I send the test data?

**Comment by wtclarke** [comment]
You can send it to the email listed at https://www.win.ox.ac.uk/people/william-clarke. Thanks

**Comment by wtclarke** [comment]
Hi @gaunab did you send me any test data? Sorry if I missed an email.

**Comment by wtclarke** [comment]
P.s. this PR seems to have got a little mangled, reverting ym most recent commit, so I have made a new PR #112 that implements just your fix. Before merging I will wait on some test data.

**Comment by gaunab** [comment]
> Hi @gaunab did you send me any test data? Sorry if I missed an email.



> Hi @gaunab did you send me any test data? Sorry if I missed an email.
I just sent test data right now, sorry for the long delay

**Pull request closed without merging**
